name: mtei
description: Mtei mobile payment

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  auto_route: ^0.6.9
  http: ^0.12.2
  path: ^1.7.0
  dio: ^3.0.10
  path_provider: ^1.6.22
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+2
  sqflite: ^1.3.1+2
  transformer_page_view: ^0.1.6
  intl_phone_number_input: ^0.5.1
  url_launcher: ^5.7.10
  flutter_datetime_picker: ^1.3.8

dev_dependencies:
  build_runner:
  auto_route_generator: ^0.6.8
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700